const REPO='rizzonicola/Scripta',API=`https://api.github.com/repos/${REPO}/releases`;
/* Testi statici (nav, hero, features, footer, banner cookie...) vivono ora
   direttamente nell'HTML di /it/ /en/ /fr/ per essere indicizzabili dai
   motori di ricerca. Qui restano solo le stringhe generate dinamicamente
   lato client (bottone download, guide di installazione, elenco release). */
const T={
it:{more:'Vedi tutte le versioni',download:'Scarica',how:'Come installare',ver:'Versione',all:'Tutti i file di installazione',prev:'Release precedenti',open:'Apri su GitHub',err:'Impossibile contattare GitHub.',loading:'Caricamento…',
g:{ios:'<h3>Installare su iOS (IPA non firmato)</h3><p>Il download è partito. Il file non è firmato da Apple, quindi va firmato con il tuo Apple ID. La procedura è la stessa in UE e fuori UE: lo store AltStore PAL non può installare IPA personali.</p><ol><li>Una sola volta, da un computer: scarica <b>iloader</b> (docs.sidestore.io), collega l\'iPhone via USB, accedi con il tuo Apple ID e installa <b>SideStore</b>.</li><li>Sull\'iPhone: Impostazioni → Generali → VPN e gestione dispositivi → fidati del tuo Apple ID. Poi Impostazioni → Privacy e sicurezza → <b>Modalità sviluppatore</b> → attiva e riavvia.</li><li>Installa <b>LocalDevVPN</b> dall\'App Store e tocca <b>Connect</b>. Apri SideStore, accedi con lo stesso Apple ID e in My Apps tocca il contatore «7 DAYS» accanto a SideStore.</li><li>In SideStore → My Apps → <b>+</b> e scegli <code>Scripta-ios-unsigned.ipa</code> dai File.</li></ol><p>Con un Apple ID gratuito l\'app scade dopo 7 giorni: SideStore la rinnova da solo se LocalDevVPN è attivo e sei in Wi-Fi. Limite: 3 app (SideStore incluso). In alternativa puoi usare AltStore (con AltServer su PC/Mac) o Sideloadly.</p>',linux:'<h3>Installare su Linux</h3><p>Il file <code>Scripta.flatpak</code> è stato scaricato (di solito in Download). Spostalo, ad esempio, in Documenti e installalo dal terminale:</p><pre>mv ~/Download/Scripta.flatpak ~/Documenti/\ncd ~/Documenti\nflatpak install --user Scripta.flatpak</pre><p>Poi avvialo dal menu applicazioni. Serve <code>flatpak</code> installato.</p>',android:'<h3>Installare su Android</h3><ol><li>Scarica l\'APK (arm64-v8a per quasi tutti i telefoni recenti; universal se in dubbio).</li><li>Consenti «Installa app sconosciute» per il browser/gestore file.</li><li>Apri l\'APK e conferma; se Play Protect avvisa, scegli «Installa comunque».</li></ol>',windows:'<h3>Installare su Windows</h3><ol><li>Scarica l\'installer x64 (o ARM64 per dispositivi Snapdragon).</li><li>Se compare SmartScreen: <b>Ulteriori informazioni → Esegui comunque</b> (app non firmata).</li></ol>',macos:'<h3>Installare su macOS</h3><ol><li>Apri il DMG e trascina Scripta in Applicazioni.</li><li>Se Gatekeeper blocca l\'app: tasto destro → Apri, oppure Impostazioni → Privacy e sicurezza → «Apri comunque».</li><li>Da terminale: <code>xattr -dr com.apple.quarantine /Applications/Scripta.app</code></li></ol>'}},
en:{more:'See all releases',download:'Download',how:'How to install',ver:'Version',all:'All install files',prev:'Previous releases',open:'Open on GitHub',err:'Could not reach GitHub.',loading:'Loading…',
g:{ios:'<h3>Install on iOS (unsigned IPA)</h3><p>Your download has started. The file is not signed by Apple, so it must be signed with your own Apple ID. The steps are the same in the EU and elsewhere: the AltStore PAL marketplace cannot install personal IPA files.</p><ol><li>Once, from a computer: download <b>iloader</b> (docs.sidestore.io), connect your iPhone by USB, sign in with your Apple ID and install <b>SideStore</b>.</li><li>On the iPhone: Settings → General → VPN & Device Management → trust your Apple ID. Then Settings → Privacy & Security → <b>Developer Mode</b> → turn on and restart.</li><li>Install <b>LocalDevVPN</b> from the App Store and tap <b>Connect</b>. Open SideStore, sign in with the same Apple ID and, in My Apps, tap the “7 DAYS” counter next to SideStore.</li><li>In SideStore → My Apps → <b>+</b> and pick <code>Scripta-ios-unsigned.ipa</code> from Files.</li></ol><p>With a free Apple ID the app expires after 7 days: SideStore refreshes it by itself while LocalDevVPN is on and you are on Wi-Fi. Limit: 3 apps (SideStore included). Alternatives: AltStore (with AltServer on PC/Mac) or Sideloadly.</p>',linux:'<h3>Install on Linux</h3><p><code>Scripta.flatpak</code> has been downloaded (usually to Downloads). Move it, e.g., to Documents and install from the terminal:</p><pre>mv ~/Downloads/Scripta.flatpak ~/Documents/\ncd ~/Documents\nflatpak install --user Scripta.flatpak</pre><p>Then launch it from your app menu. Requires <code>flatpak</code>.</p>',android:'<h3>Install on Android</h3><ol><li>Download the APK (arm64-v8a suits most recent phones; universal if unsure).</li><li>Allow “Install unknown apps” for your browser/file manager.</li><li>Open the APK; if Play Protect warns, choose “Install anyway”.</li></ol>',windows:'<h3>Install on Windows</h3><ol><li>Download the x64 installer (ARM64 for Snapdragon devices).</li><li>If SmartScreen appears: <b>More info → Run anyway</b> (unsigned app).</li></ol>',macos:'<h3>Install on macOS</h3><ol><li>Open the DMG and drag Scripta to Applications.</li><li>If Gatekeeper blocks it: right-click → Open, or System Settings → Privacy & Security → “Open Anyway”.</li><li>Terminal: <code>xattr -dr com.apple.quarantine /Applications/Scripta.app</code></li></ol>'}},
fr:{more:'Voir toutes les versions',download:'Télécharger',how:'Comment installer',ver:'Version',all:'Tous les fichiers d\'installation',prev:'Versions précédentes',open:'Ouvrir sur GitHub',err:'Impossible de joindre GitHub.',loading:'Chargement…',
g:{ios:'<h3>Installer sur iOS (IPA non signé)</h3><p>Le téléchargement a démarré. Le fichier n\'est pas signé par Apple : il doit être signé avec votre propre identifiant Apple. La procédure est la même dans l\'UE et ailleurs : la boutique AltStore PAL ne peut pas installer d\'IPA personnels.</p><ol><li>Une seule fois, depuis un ordinateur : téléchargez <b>iloader</b> (docs.sidestore.io), branchez l\'iPhone en USB, connectez-vous avec votre identifiant Apple et installez <b>SideStore</b>.</li><li>Sur l\'iPhone : Réglages → Général → VPN et gestion de l\'appareil → faites confiance à votre identifiant Apple. Puis Réglages → Confidentialité et sécurité → <b>Mode développeur</b> → activez et redémarrez.</li><li>Installez <b>LocalDevVPN</b> depuis l\'App Store et touchez <b>Connect</b>. Ouvrez SideStore, connectez-vous avec le même identifiant et, dans My Apps, touchez le compteur « 7 DAYS » à côté de SideStore.</li><li>Dans SideStore → My Apps → <b>+</b> et choisissez <code>Scripta-ios-unsigned.ipa</code> depuis Fichiers.</li></ol><p>Avec un identifiant Apple gratuit, l\'app expire après 7 jours : SideStore la renouvelle seul si LocalDevVPN est actif et que vous êtes en Wi-Fi. Limite : 3 apps (SideStore inclus). Alternatives : AltStore (avec AltServer sur PC/Mac) ou Sideloadly.</p>',linux:'<h3>Installer sur Linux</h3><p><code>Scripta.flatpak</code> a été téléchargé (souvent dans Téléchargements). Déplacez-le, par ex., dans Documents et installez-le depuis le terminal :</p><pre>mv ~/Téléchargements/Scripta.flatpak ~/Documents/\ncd ~/Documents\nflatpak install --user Scripta.flatpak</pre><p>Puis lancez-le depuis le menu des applications. Nécessite <code>flatpak</code>.</p>',android:'<h3>Installer sur Android</h3><ol><li>Téléchargez l\'APK (arm64-v8a pour la plupart des téléphones récents ; universal en cas de doute).</li><li>Autorisez « Installer des applis inconnues » pour votre navigateur.</li><li>Ouvrez l\'APK ; si Play Protect avertit, choisissez « Installer quand même ».</li></ol>',windows:'<h3>Installer sur Windows</h3><ol><li>Téléchargez l\'installeur x64 (ARM64 pour Snapdragon).</li><li>Si SmartScreen apparaît : <b>Informations complémentaires → Exécuter quand même</b> (app non signée).</li></ol>',macos:'<h3>Installer sur macOS</h3><ol><li>Ouvrez le DMG et glissez Scripta dans Applications.</li><li>Si Gatekeeper bloque : clic droit → Ouvrir, ou Réglages → Confidentialité et sécurité → « Ouvrir quand même ».</li><li>Terminal : <code>xattr -dr com.apple.quarantine /Applications/Scripta.app</code></li></ol>'}}
};
const $=s=>document.querySelector(s),ls={get:k=>{try{return localStorage.getItem(k)}catch(e){return null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}}};
const OS={android:{n:'Android'},ios:{n:'iOS'},macos:{n:'macOS'},windows:{n:'Windows'},linux:{n:'Linux'}};
const ICON={android:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M5 14a7 7 0 0 1 14 0z"/><rect x="5" y="15.5" width="14" height="6" rx="2"/><path d="M8 5.5L6.6 3.4M16 5.5l1.4-2.1" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',ios:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6.5" y="2" width="11" height="20" rx="3" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M10.5 18.5h3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',macos:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="3" y="4" width="18" height="12.5" rx="2.2" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M8 20.5h8M12 16.5v4" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>',windows:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="3" y="3" width="8.3" height="8.3" rx="1"/><rect x="12.7" y="3" width="8.3" height="8.3" rx="1"/><rect x="3" y="12.7" width="8.3" height="8.3" rx="1"/><rect x="12.7" y="12.7" width="8.3" height="8.3" rx="1"/></svg>',linux:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="2.5" y="4" width="19" height="16" rx="2.5" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M7 9.5l3.5 2.5L7 14.5M12.5 15h4.5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'};

/* La lingua della pagina è fissa (impostata nel markup statico), non più
   indovinata: SEO-safe, un URL = una lingua. */
const lang=document.documentElement.dataset.lang||document.documentElement.lang||'it';
const page=document.body.dataset.page||'home'; // 'home' | 'releases'
let rels=[],os='linux',arch='x64';

function detect(){const u=navigator.userAgent,ud=navigator.userAgentData;
 if(/android/i.test(u))os='android';else if(/iPhone|iPad|iPod/i.test(u)||(/Mac/.test(u)&&navigator.maxTouchPoints>1))os='ios';else if(/Mac/i.test(u))os='macos';else if(/Win/i.test(u))os='windows';else os='linux';
 if(/arm64|aarch64|ARM/i.test(u))arch='arm64';
 if(ud&&ud.getHighEntropyValues)ud.getHighEntropyValues(['architecture']).then(h=>{if(h.architecture==='arm'){arch='arm64';renderHero()}}).catch(()=>{})}
const fmt=b=>b>1e6?(b/1e6).toFixed(1)+' MB':(b/1e3).toFixed(0)+' KB';
function pick(assets,o,a){const f=r=>assets.find(x=>r.test(x.name));
 if(o==='android')return f(/universal.*\.apk$/i)||f(/arm64-v8a.*\.apk$/i)||f(/\.apk$/i);
 if(o==='ios')return f(/\.ipa$/i);
 if(o==='macos')return f(/universal.*\.dmg$/i)||f(/\.dmg$/i)||f(/macos.*\.zip$/i);
 if(o==='windows')return(a==='arm64'&&f(/arm64.*\.exe$/i))||f(/x64.*\.exe$/i)||f(/\.exe$/i);
 return f(/\.flatpak$/i)}
function t(k){return T[lang][k]}
const MORE=`https://github.com/${REPO}/releases/`,DL=`https://github.com/${REPO}/releases/latest/download/`;
function sf(){return {android:'Scripta-universal.apk',ios:'Scripta-ios-unsigned.ipa',macos:'Scripta-macos-universal.dmg',windows:`Scripta-windows-${arch==='arm64'?'arm64':'x64'}-setup.exe`,linux:'Scripta.flatpak'}[os]}
function renderHero(){if(page!=='home')return;const r=rels[0],o=OS[os],auto=os==='ios'||os==='linux',a=r&&pick(r.assets,os,arch);
 $('#cta').innerHTML=`<a class="btn pri" id="dlBtn" href="${a?a.browser_download_url:DL+sf()}">${ICON[os]} ${t('download')} · ${o.n}</a><div class="sm"><a href="${MORE}" target="_blank" rel="noopener">${t('more')}</a><a href="#" id="hw">${t('how')}</a></div>`;
 const d=$('#dlBtn');if(auto)d.onclick=()=>setTimeout(()=>guide(os),300);
 $('#hw').onclick=e=>{e.preventDefault();guide(os)};
 $('#meta').textContent=r?`${t('ver')} ${r.tag_name} · ${new Date(r.published_at).toLocaleDateString(lang)}`+(a?` · ${a.name} (${fmt(a.size)})`:''):''}
function guide(k){$('#gBody').innerHTML=t('g')[k];$('#guide').showModal()}
function assetRow(a){const d=a.digest?a.digest.replace('sha256:',''):'';return `<div class="row"><div><a href="${a.browser_download_url}">${a.name}</a> <span style="color:var(--mu)">· ${fmt(a.size)}</span>${d?`<small>sha256: ${d}</small>`:''}</div></div>`}
function renderRel(){if(page!=='releases')return;const p=$('#rel');if(!rels.length)return; // il markup statico resta finché non arrivano i dati
 const r=rels[0];p.innerHTML=`<div class="panel"><h3>${r.name||r.tag_name}<span class="badge">Latest</span></h3><p style="color:var(--mu)">${t('all')}</p>`+r.assets.map(assetRow).join('')+`<p><a href="${r.html_url}" rel="noopener">${t('open')} →</a></p></div><h3 style="margin:32px 0 12px">${t('prev')}</h3>`+
 rels.slice(1).map(r=>`<details class="panel" style="margin-bottom:10px"><summary><b>${r.tag_name}</b> <span style="color:var(--mu)">· ${new Date(r.published_at).toLocaleDateString(lang)}</span></summary>${r.assets.map(assetRow).join('')||'—'}<p><a href="${r.html_url}" rel="noopener">${t('open')} →</a></p></details>`).join('')}
async function getRels(){try{const r=await fetch('/releases.json',{cache:'no-cache'});if(r.ok){const j=await r.json();if(Array.isArray(j)&&j.length)return j}}catch(e){}
 const r=await fetch(API+'?per_page=30',{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw 0;return r.json()}
async function load(){const c=ls.get('sc_cache'),ok=ls.get('sc_opt')==='1';
 if(ok&&c){try{const j=JSON.parse(c);if(Date.now()-j.t<36e5){rels=j.d;renderHero();renderRel();return}}catch(e){}}
 try{rels=(await getRels()).filter(x=>!x.draft&&!x.prerelease);
  if(ok)ls.set('sc_cache',JSON.stringify({t:Date.now(),d:rels}));renderHero();renderRel()}
 catch(e){if(page==='releases')$('#rel').innerHTML=`<p>${t('err')} <a href="https://github.com/${REPO}/releases">${t('open')} →</a></p>`}}
$('#setBtn').onclick=()=>{$('#optSw').checked=ls.get('sc_opt')==='1';$('#set').showModal()};
$('#optSw').onchange=e=>{ls.set('sc_opt',e.target.checked?'1':'0');if(!e.target.checked)try{localStorage.removeItem('sc_cache')}catch(_){}};
function openPriv(){$('#set').close();ck.hidden=false;$('#prefs').hidden=false;$('#optCache').checked=ls.get('sc_opt')==='1';$('#cus').textContent='OK'}
$('#stRead').onclick=e=>{e.preventDefault();openPriv()};
function pressed(id,v){document.querySelectorAll(id+' button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.v===v))}
/* Il cambio lingua ora naviga verso /<lang>/ o /<lang>/releases/: un URL
   statico per lingua, indicizzabile e con hreflang corretto, invece di
   riscrivere il testo via JS in un unico URL. */
$('#langSeg').onclick=e=>{const v=e.target.dataset.v;if(!v||v===lang)return;ls.set('sc_lang',v);
 const p=e.target.closest('[data-page]').dataset.page;location.href='/'+v+(p==='releases'?'/releases/':'/')};
$('#themeSeg').onclick=e=>{const v=e.target.dataset.v;if(v){document.documentElement.dataset.theme=v;ls.set('sc_theme',v);pressed('#themeSeg',v)}};
const th=ls.get('sc_theme')||'dark';document.documentElement.dataset.theme=th;pressed('#themeSeg',th);
const ck=$('#ck');function done(opt){ls.set('sc_consent','1');ls.set('sc_opt',opt?'1':'0');if(!opt)try{localStorage.removeItem('sc_cache')}catch(e){}ck.hidden=true}
$('#acc').onclick=()=>done(true);$('#rej').onclick=()=>done(false);
$('#cus').onclick=()=>{const p=$('#prefs');if(p.hidden){p.hidden=false;$('#optCache').checked=ls.get('sc_opt')==='1';$('#cus').textContent='OK'}else done($('#optCache').checked)};
$('#privL').onclick=e=>{e.preventDefault();openPriv()};
if(!ls.get('sc_consent'))ck.hidden=false;
detect();renderHero();load();

