const REPO='rizzonicola/Scripta',API=`https://api.github.com/repos/${REPO}/releases`;
const T={
it:{more:'Altro',st_priv:'Privacy e cookie',st_read:'Leggi l\'informativa completa',download:'Scarica',back:'← Indietro',prev:'Release precedenti',settings:'Impostazioni',nav_f:'Funzioni',nav_d:'Download',nav_a:'Licenze',tag:"Editor di note open source e local-first. Markdown puro, ricerca istantanea, sincronizzazione self-hosted. Per tutti i tuoi dispositivi.",loading:'Caricamento…',feat:'Pensata per scrivere',dl:'Download',t_cur:'Versione corrente',t_old:'Release precedenti',lic_h:'Informazioni & Licenze',lic_p:'Scripta è rilasciata con licenza GPL-3.0 ed è costruita su software open source. Grazie ai loro sviluppatori.',foot:'© Scripta · GPL-3.0',priv:'Privacy & cookie',close:'Chiudi',lang:'Lingua',theme:'Tema',th_d:'Scuro',th_l:'Chiaro',th_c:'Alto contrasto',
ck_t:'Privacy e cookie',ck_p1:'Questo sito usa solo cookie/storage strettamente necessari (lingua e tema scelti). Nessuna profilazione, nessuna vendita di dati a terzi.',ck_p2:'Il traffico può transitare da Cloudflare (anche via Cloudflare Tunnel), che tratta indirizzo IP di origine, User-Agent e log di sicurezza per mitigare attacchi DDoS. Le informazioni sulle release sono richieste direttamente all\'API pubblica di GitHub dal tuo browser (GitHub riceve il tuo IP).',ck_p3:'Base giuridica: legittimo interesse (art. 6.1.f GDPR) per sicurezza e funzionamento; consenso per il resto. Puoi cambiare idea da Impostazioni → Privacy. L\'app Scripta è local-first: le note restano sul tuo dispositivo o sul tuo server.',ck_nec:'Necessari: lingua, tema, scelta cookie',ck_opt:'Facoltativo: memorizza in cache le release per 1 ora (riduce le chiamate a GitHub)',ck_all:'Accetta tutti',ck_rej:'Rifiuta non essenziali',ck_cus:'Personalizza',
dlfor:'Scarica per',ver:'Versione',allf:'Tutti i file / altre versioni',how:'Come installare',other:'Altre architetture o versioni (GitHub)',noasset:'Nessun file per il tuo sistema: vedi tutti i file.',err:'Impossibile contattare GitHub.',open:'Apri su GitHub',all:'Tutti i file di installazione',size:'Dimensione',
f:[['Editor Markdown','Sintassi evidenziata, toolbar intelligente e vista di lettura istantanea.'],['Local-first','Avvio immediato e ricerca rapidissima con SQLite WAL. Funziona offline.'],['Sincronizzazione','Sync asincrona con backend self-hosted, risoluzione Last-Write-Wins.'],['Cartelle annidate','Preferiti, note fissate e drag & drop.'],['Tuoi dati','Import/export ZIP o file Markdown. Nessun lock-in.'],['Multipiattaforma','Android, iOS, macOS, Windows e Linux.']],
g:{ios:'<h3>Installare su iOS (IPA non firmato)</h3><p>Il download è partito. Scegli il metodo:</p><h4>Se sei nell\'UE</h4><ol><li>Installa <b>AltStore PAL</b> (Alternative App Marketplace, iOS 17.4+ / 26+) dal sito ufficiale.</li><li>In AltStore → Sources/My Apps → <b>+</b> e seleziona <code>Scripta-ios-unsigned.ipa</code> dai File.</li></ol><h4>Fuori dall\'UE</h4><ol><li>Installa <b>SideStore</b> (o AltStore/Sideloadly da computer) con il tuo Apple ID.</li><li>Attiva la VPN locale di SideStore: rinnova e riavvia automaticamente l\'app ogni 7 giorni senza computer.</li><li>Apri l\'IPA con SideStore e, in Impostazioni → Generali → VPN e gestione dispositivi, fidati del profilo.</li></ol>',linux:'<h3>Installare su Linux</h3><p>Il file <code>Scripta.flatpak</code> è stato scaricato (di solito in Download). Spostalo, ad esempio, in Documenti e installalo dal terminale:</p><pre>mv ~/Download/Scripta.flatpak ~/Documenti/\ncd ~/Documenti\nflatpak install --user Scripta.flatpak</pre><p>Poi avvialo dal menu applicazioni. Serve <code>flatpak</code> installato.</p>',android:'<h3>Installare su Android</h3><ol><li>Scarica l\'APK (arm64-v8a per quasi tutti i telefoni recenti; universal se in dubbio).</li><li>Consenti «Installa app sconosciute» per il browser/gestore file.</li><li>Apri l\'APK e conferma; se Play Protect avvisa, scegli «Installa comunque».</li></ol>',windows:'<h3>Installare su Windows</h3><ol><li>Scarica l\'installer x64 (o ARM64 per dispositivi Snapdragon).</li><li>Se compare SmartScreen: <b>Ulteriori informazioni → Esegui comunque</b> (app non firmata).</li></ol>',macos:'<h3>Installare su macOS</h3><ol><li>Apri il DMG e trascina Scripta in Applicazioni.</li><li>Se Gatekeeper blocca l\'app: tasto destro → Apri, oppure Impostazioni → Privacy e sicurezza → «Apri comunque».</li><li>Da terminale: <code>xattr -dr com.apple.quarantine /Applications/Scripta.app</code></li></ol>'}},
en:{more:'More',st_priv:'Privacy & cookies',st_read:'Read the full privacy notice',download:'Download',back:'← Back',prev:'Previous releases',settings:'Settings',nav_f:'Features',nav_d:'Download',nav_a:'Licenses',tag:'Open-source, local-first note-taking. Raw Markdown, instant search, self-hosted sync. On all your devices.',loading:'Loading…',feat:'Built for writing',dl:'Download',t_cur:'Current version',t_old:'Previous releases',lic_h:'About & Licenses',lic_p:'Scripta is released under GPL-3.0 and built on open-source software. Thanks to all their developers.',foot:'© Scripta · GPL-3.0',priv:'Privacy & cookies',close:'Close',lang:'Language',theme:'Theme',th_d:'Dark',th_l:'Light',th_c:'High contrast',
ck_t:'Privacy & cookies',ck_p1:'This site only uses strictly necessary cookies/storage (your language and theme). No profiling, no selling data to third parties.',ck_p2:'Traffic may pass through Cloudflare (including Cloudflare Tunnel), which processes source IP address, User-Agent and security logs to mitigate DDoS attacks. Release info is requested from the public GitHub API directly by your browser (GitHub sees your IP).',ck_p3:'Legal basis: legitimate interest (Art. 6.1.f GDPR) for security and operation; consent for everything else. Change your mind anytime in Settings → Privacy. The Scripta app is local-first: notes stay on your device or your own server.',ck_nec:'Necessary: language, theme, cookie choice',ck_opt:'Optional: cache releases for 1 hour (fewer GitHub calls)',ck_all:'Accept all',ck_rej:'Reject non-essential',ck_cus:'Customize',
dlfor:'Download for',ver:'Version',allf:'All files / other versions',how:'How to install',other:'Other architectures or versions (GitHub)',noasset:'No file for your system: see all files.',err:'Could not reach GitHub.',open:'Open on GitHub',all:'All install files',size:'Size',
f:[['Markdown editor','Syntax highlighting, smart toolbar and an instant reading view.'],['Local-first','Instant startup and lightning search via SQLite WAL. Works offline.'],['Sync','Async sync with self-hosted backends, Last-Write-Wins resolution.'],['Nested folders','Favorites, pinned notes and drag & drop.'],['Your data','ZIP or Markdown import/export. No lock-in.'],['Cross-platform','Android, iOS, macOS, Windows and Linux.']],
g:{ios:'<h3>Install on iOS (unsigned IPA)</h3><p>Your download has started. Pick a method:</p><h4>If you are in the EU</h4><ol><li>Install <b>AltStore PAL</b> (Alternative App Marketplace, iOS 17.4+ / 26+) from its official site.</li><li>In AltStore → Sources/My Apps → <b>+</b> and select <code>Scripta-ios-unsigned.ipa</code> from Files.</li></ol><h4>Outside the EU</h4><ol><li>Install <b>SideStore</b> (or AltStore/Sideloadly from a computer) using your Apple ID.</li><li>Enable SideStore\'s local VPN: it refreshes and relaunches the app automatically every 7 days, no computer needed.</li><li>Open the IPA with SideStore and trust the profile in Settings → General → VPN & Device Management.</li></ol>',linux:'<h3>Install on Linux</h3><p><code>Scripta.flatpak</code> has been downloaded (usually to Downloads). Move it, e.g., to Documents and install from the terminal:</p><pre>mv ~/Downloads/Scripta.flatpak ~/Documents/\ncd ~/Documents\nflatpak install --user Scripta.flatpak</pre><p>Then launch it from your app menu. Requires <code>flatpak</code>.</p>',android:'<h3>Install on Android</h3><ol><li>Download the APK (arm64-v8a suits most recent phones; universal if unsure).</li><li>Allow “Install unknown apps” for your browser/file manager.</li><li>Open the APK; if Play Protect warns, choose “Install anyway”.</li></ol>',windows:'<h3>Install on Windows</h3><ol><li>Download the x64 installer (ARM64 for Snapdragon devices).</li><li>If SmartScreen appears: <b>More info → Run anyway</b> (unsigned app).</li></ol>',macos:'<h3>Install on macOS</h3><ol><li>Open the DMG and drag Scripta to Applications.</li><li>If Gatekeeper blocks it: right-click → Open, or System Settings → Privacy & Security → “Open Anyway”.</li><li>Terminal: <code>xattr -dr com.apple.quarantine /Applications/Scripta.app</code></li></ol>'}},
fr:{more:'Plus',st_priv:'Confidentialité et cookies',st_read:'Lire l\'information complète',download:'Télécharger',back:'← Retour',prev:'Versions précédentes',settings:'Réglages',nav_f:'Fonctions',nav_d:'Télécharger',nav_a:'Licences',tag:'Prise de notes open source et local-first. Markdown pur, recherche instantanée, synchronisation auto-hébergée. Sur tous vos appareils.',loading:'Chargement…',feat:'Conçue pour écrire',dl:'Téléchargement',t_cur:'Version actuelle',t_old:'Versions précédentes',lic_h:'À propos & Licences',lic_p:'Scripta est publiée sous licence GPL-3.0 et repose sur des logiciels open source. Merci à leurs développeurs.',foot:'© Scripta · GPL-3.0',priv:'Confidentialité & cookies',close:'Fermer',lang:'Langue',theme:'Thème',th_d:'Sombre',th_l:'Clair',th_c:'Contraste élevé',
ck_t:'Confidentialité et cookies',ck_p1:'Ce site n\'utilise que des cookies/stockages strictement nécessaires (langue et thème). Aucun profilage, aucune vente de données à des tiers.',ck_p2:'Le trafic peut transiter par Cloudflare (y compris Cloudflare Tunnel), qui traite l\'adresse IP source, le User-Agent et des journaux de sécurité pour atténuer les attaques DDoS. Les informations de version sont demandées directement à l\'API publique de GitHub par votre navigateur (GitHub voit votre IP).',ck_p3:'Base juridique : intérêt légitime (art. 6.1.f RGPD) pour la sécurité et le fonctionnement ; consentement pour le reste. Modifiable à tout moment dans Réglages → Confidentialité. L\'app Scripta est local-first : vos notes restent sur votre appareil ou votre serveur.',ck_nec:'Nécessaires : langue, thème, choix des cookies',ck_opt:'Facultatif : mettre en cache les versions 1 h (moins d\'appels à GitHub)',ck_all:'Tout accepter',ck_rej:'Refuser le non essentiel',ck_cus:'Personnaliser',
dlfor:'Télécharger pour',ver:'Version',allf:'Tous les fichiers / autres versions',how:'Comment installer',other:'Autres architectures ou versions (GitHub)',noasset:'Aucun fichier pour votre système : voir tous les fichiers.',err:'Impossible de joindre GitHub.',open:'Ouvrir sur GitHub',all:'Tous les fichiers d\'installation',size:'Taille',
f:[['Éditeur Markdown','Coloration syntaxique, barre d\'outils intelligente et lecture instantanée.'],['Local-first','Démarrage immédiat et recherche ultra-rapide (SQLite WAL). Hors ligne.'],['Synchronisation','Sync asynchrone avec serveurs auto-hébergés, résolution Last-Write-Wins.'],['Dossiers imbriqués','Favoris, notes épinglées et glisser-déposer.'],['Vos données','Import/export ZIP ou Markdown. Aucun verrouillage.'],['Multiplateforme','Android, iOS, macOS, Windows et Linux.']],
g:{ios:'<h3>Installer sur iOS (IPA non signé)</h3><p>Le téléchargement a démarré. Choisissez une méthode :</p><h4>Dans l\'UE</h4><ol><li>Installez <b>AltStore PAL</b> (Alternative App Marketplace, iOS 17.4+ / 26+) depuis le site officiel.</li><li>Dans AltStore → Sources/My Apps → <b>+</b> et sélectionnez <code>Scripta-ios-unsigned.ipa</code> depuis Fichiers.</li></ol><h4>Hors UE</h4><ol><li>Installez <b>SideStore</b> (ou AltStore/Sideloadly depuis un ordinateur) avec votre Apple ID.</li><li>Activez le VPN local de SideStore : il renouvelle et relance l\'app automatiquement tous les 7 jours, sans ordinateur.</li><li>Ouvrez l\'IPA avec SideStore et faites confiance au profil dans Réglages → Général → VPN et gestion de l\'appareil.</li></ol>',linux:'<h3>Installer sur Linux</h3><p><code>Scripta.flatpak</code> a été téléchargé (souvent dans Téléchargements). Déplacez-le, par ex., dans Documents et installez-le depuis le terminal :</p><pre>mv ~/Téléchargements/Scripta.flatpak ~/Documents/\ncd ~/Documents\nflatpak install --user Scripta.flatpak</pre><p>Puis lancez-le depuis le menu des applications. Nécessite <code>flatpak</code>.</p>',android:'<h3>Installer sur Android</h3><ol><li>Téléchargez l\'APK (arm64-v8a pour la plupart des téléphones récents ; universal en cas de doute).</li><li>Autorisez « Installer des applis inconnues » pour votre navigateur.</li><li>Ouvrez l\'APK ; si Play Protect avertit, choisissez « Installer quand même ».</li></ol>',windows:'<h3>Installer sur Windows</h3><ol><li>Téléchargez l\'installeur x64 (ARM64 pour Snapdragon).</li><li>Si SmartScreen apparaît : <b>Informations complémentaires → Exécuter quand même</b> (app non signée).</li></ol>',macos:'<h3>Installer sur macOS</h3><ol><li>Ouvrez le DMG et glissez Scripta dans Applications.</li><li>Si Gatekeeper bloque : clic droit → Ouvrir, ou Réglages → Confidentialité et sécurité → « Ouvrir quand même ».</li><li>Terminal : <code>xattr -dr com.apple.quarantine /Applications/Scripta.app</code></li></ol>'}}
};
const LIBS=[['Flutter / flutter_localizations','BSD-3-Clause'],['flutter_riverpod','MIT'],['flutter_md','see pub.dev'],['flutter_math_fork','Apache-2.0 / MIT'],['shared_preferences','BSD-3-Clause'],['sqflite / sqflite_common_ffi','BSD-2-Clause'],['path / path_provider','BSD-3-Clause'],['google_fonts','Apache-2.0'],['uuid','MIT'],['url_launcher','BSD-3-Clause'],['archive','MIT'],['file_picker','MIT'],['flutter_secure_storage','BSD-3-Clause'],['http','BSD-3-Clause']];
const $=s=>document.querySelector(s),ls={get:k=>{try{return localStorage.getItem(k)}catch(e){return null}},set:(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}}};
const OS={android:{n:'Android'},ios:{n:'iOS'},macos:{n:'macOS'},windows:{n:'Windows'},linux:{n:'Linux'}};
const ICON={android:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M5 14a7 7 0 0 1 14 0z"/><rect x="5" y="15.5" width="14" height="6" rx="2"/><path d="M8 5.5L6.6 3.4M16 5.5l1.4-2.1" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>',ios:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="6.5" y="2" width="11" height="20" rx="3" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M10.5 18.5h3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>',macos:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="3" y="4" width="18" height="12.5" rx="2.2" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M8 20.5h8M12 16.5v4" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>',windows:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="3" y="3" width="8.3" height="8.3" rx="1"/><rect x="12.7" y="3" width="8.3" height="8.3" rx="1"/><rect x="3" y="12.7" width="8.3" height="8.3" rx="1"/><rect x="12.7" y="12.7" width="8.3" height="8.3" rx="1"/></svg>',linux:'<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><rect x="2.5" y="4" width="19" height="16" rx="2.5" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M7 9.5l3.5 2.5L7 14.5M12.5 15h4.5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'};
let lang=ls.get('sc_lang')||(navigator.language||'it').slice(0,2);if(!T[lang])lang='en';
let rels=[],os='linux',arch='x64';
function detect(){const u=navigator.userAgent,ud=navigator.userAgentData;
 if(/android/i.test(u))os='android';else if(/iPhone|iPad|iPod/i.test(u)||(/Mac/.test(u)&&navigator.maxTouchPoints>1))os='ios';else if(/Mac/i.test(u))os='macos';else if(/Win/i.test(u))os='windows';else os='linux';
 if(/arm64|aarch64|ARM/i.test(u))arch='arm64';
 if(ud&&ud.getHighEntropyValues)ud.getHighEntropyValues(['architecture']).then(h=>{if(h.architecture==='arm'){arch='arm64';renderHero()}}).catch(()=>{})}
const fmt=b=>b>1e6?(b/1e6).toFixed(1)+' MB':(b/1e3).toFixed(0)+' KB';
function pick(assets,o,a){const f=r=>assets.find(x=>r.test(x.name));
 if(o==='android')return f(/universal.*\.apk$/i)||f(/arm64-v8a.*\.apk$/i)||f(/\.apk$/i);
 if(o==='ios')return f(/\.ipa$/i);
 if(o==='macos')return f(/universal.*\.dmg$/i)||f(/\.dmg$/i)||f(/macos.*\.zip$/i);
 if(o==='windows')return(a==='arm64'&&f(/arm64.*\.exe$/i))||f(/x64.*\.exe$/i)||f(/\.exe$/i);
 return f(/\.flatpak$/i)}
function t(k){return T[lang][k]}
function applyI18n(){document.documentElement.lang=lang;document.querySelectorAll('[data-i]').forEach(e=>e.textContent=t(e.dataset.i));
 $('#fgrid').innerHTML=t('f').map(f=>`<div class="card"><h3>${f[0]}</h3><p>${f[1]}</p></div>`).join('');
 $('#lics').innerHTML=LIBS.map(l=>`<div class="lic">${l[0]}<span>${l[1]}</span></div>`).join('')+`<div class="lic"><b>Scripta</b><span>GPL-3.0</span></div>`;
 pressed('#langSeg',lang);renderHero();renderRel()}
const MORE=`https://github.com/${REPO}/releases/`,DL=`https://github.com/${REPO}/releases/latest/download/`;
function sf(){return {android:'Scripta-universal.apk',ios:'Scripta-ios-unsigned.ipa',macos:'Scripta-macos-universal.dmg',windows:`Scripta-windows-${arch==='arm64'?'arm64':'x64'}-setup.exe`,linux:'Scripta.flatpak'}[os]}
function renderHero(){const r=rels[0],o=OS[os],auto=os==='ios'||os==='linux',a=r&&pick(r.assets,os,arch);
 $('#cta').innerHTML=`<a class="btn pri" id="dlBtn" href="${a?a.browser_download_url:DL+sf()}">${ICON[os]} ${t('download')} · ${o.n}</a><div class="sm"><a href="${MORE}" target="_blank" rel="noopener">${t('more')}</a><a href="#" id="hw">${t('how')}</a></div>`;
 const d=$('#dlBtn');if(auto)d.onclick=()=>setTimeout(()=>guide(os),300);
 $('#hw').onclick=e=>{e.preventDefault();guide(os)};
 $('#meta').textContent=r?`${t('ver')} ${r.tag_name} · ${new Date(r.published_at).toLocaleDateString(lang)}`+(a?` · ${a.name} (${fmt(a.size)})`:''):''}
function guide(k){$('#gBody').innerHTML=t('g')[k];$('#guide').showModal()}
function assetRow(a){const d=a.digest?a.digest.replace('sha256:',''):'';return `<div class="row"><div><a href="${a.browser_download_url}">${a.name}</a> <span style="color:var(--mu)">· ${fmt(a.size)}</span>${d?`<small>sha256: ${d}</small>`:''}</div></div>`}
function renderRel(){const p=$('#rel');if(!rels.length){p.textContent=t('loading');return}
 const r=rels[0];p.innerHTML=`<div class="panel"><h3>${r.name||r.tag_name}<span class="badge">Latest</span></h3><p style="color:var(--mu)">${t('all')}</p>`+r.assets.map(assetRow).join('')+`<p><a href="${r.html_url}" rel="noopener">${t('open')} →</a></p></div><h3 style="margin:32px 0 12px">${t('prev')}</h3>`+
 rels.slice(1).map(r=>`<details class="panel" style="margin-bottom:10px"><summary><b>${r.tag_name}</b> <span style="color:var(--mu)">· ${new Date(r.published_at).toLocaleDateString(lang)}</span></summary>${r.assets.map(assetRow).join('')||'—'}<p><a href="${r.html_url}" rel="noopener">${t('open')} →</a></p></details>`).join('')}
function route(){const r=location.hash==='#/releases';$('#home').hidden=r;$('#relpage').hidden=!r;if(r)scrollTo(0,0)}
addEventListener('hashchange',route);
async function getRels(){try{const r=await fetch('releases.json',{cache:'no-cache'});if(r.ok){const j=await r.json();if(Array.isArray(j)&&j.length)return j}}catch(e){}
 const r=await fetch(API+'?per_page=30',{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw 0;return r.json()}
async function load(){const c=ls.get('sc_cache'),ok=ls.get('sc_opt')==='1';
 if(ok&&c){try{const j=JSON.parse(c);if(Date.now()-j.t<36e5){rels=j.d;applyI18n();return}}catch(e){}}
 try{rels=(await getRels()).filter(x=>!x.draft&&!x.prerelease);
  if(ok)ls.set('sc_cache',JSON.stringify({t:Date.now(),d:rels}));applyI18n()}
 catch(e){$('#rel').innerHTML=`<p>${t('err')} <a href="https://github.com/${REPO}/releases">${t('open')} →</a></p>`}}
$('#setBtn').onclick=()=>{$('#optSw').checked=ls.get('sc_opt')==='1';$('#set').showModal()};
$('#optSw').onchange=e=>{ls.set('sc_opt',e.target.checked?'1':'0');if(!e.target.checked)try{localStorage.removeItem('sc_cache')}catch(_){}};
function openPriv(){$('#set').close();ck.hidden=false;$('#prefs').hidden=false;$('#optCache').checked=ls.get('sc_opt')==='1';$('#cus').textContent='OK'}
$('#stRead').onclick=e=>{e.preventDefault();openPriv()};
function pressed(id,v){document.querySelectorAll(id+' button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.v===v))}
$('#langSeg').onclick=e=>{const v=e.target.dataset.v;if(v){lang=v;ls.set('sc_lang',v);applyI18n()}};
$('#themeSeg').onclick=e=>{const v=e.target.dataset.v;if(v){document.documentElement.dataset.theme=v;ls.set('sc_theme',v);pressed('#themeSeg',v)}};
const th=ls.get('sc_theme')||'dark';document.documentElement.dataset.theme=th;pressed('#themeSeg',th);
const ck=$('#ck');function done(opt){ls.set('sc_consent','1');ls.set('sc_opt',opt?'1':'0');if(!opt)try{localStorage.removeItem('sc_cache')}catch(e){}ck.hidden=true}
$('#acc').onclick=()=>done(true);$('#rej').onclick=()=>done(false);
$('#cus').onclick=()=>{const p=$('#prefs');if(p.hidden){p.hidden=false;$('#optCache').checked=ls.get('sc_opt')==='1';$('#cus').textContent='OK'}else done($('#optCache').checked)};
$('#privL').onclick=e=>{e.preventDefault();openPriv()};
if(!ls.get('sc_consent'))ck.hidden=false;
detect();applyI18n();route();load();
